### ISSUE TITLE
rc.local service failure on boot

### ISSUE THREAD

**Issue by okcrum** [AllStarLink/asl3-pi-image#15]
After updating from main to beta distrib and rebooting, rc.local service fails with an exec error. /etc/rc.local should have a first line like #!/bin/sh -e but does not. If not needed, it can be deleted.

**Comment by okcrum** [comment]
This is on RPi 3B+ to be clear.

**Comment by jxmx** [comment]
This is a bug in upstream CustomPiOS that it looks like I accidentally fixed already. I updated the patch for clarity in 79f4556..d368dbe.

**Comment by Allan-N** [comment]
Instead of :
```
echo '/bin/sh -e' > /etc/rc.local
```
I think you wanted :
```
echo '#!/bin/sh -e' > /etc/rc.local
```

**Comment by jxmx** [comment]
Fixed
